"use client";

import { useCallback, useEffect, useState } from "react";
import { fetchCloudShieldClient } from "../../../../lib/client-api";
import { toApiError, type ApiError } from "../../../../lib/api-error";
import {
  FrontendEvidenceSnapshotListSchema,
  type FrontendSecurityFindingEvidenceSnapshot
} from "../../../../lib/response-contracts";
import { ErrorState } from "../../../../components/ui/error-state";
import { LoadingState } from "../../../../components/ui/loading-state";
import { Section, SourceBadge } from "../../shared";

function formatTimestamp(value: string) {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

export function FindingEvidenceHistory({ findingId }: { findingId: string }) {
  const [items, setItems] = useState<FrontendSecurityFindingEvidenceSnapshot[]>([]);
  const [cursor, setCursor] = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(false);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);

  const load = useCallback(async (nextCursor?: string) => {
    nextCursor ? setLoadingMore(true) : setLoading(true);
    setError(null);
    try {
      const query = nextCursor ? `?cursor=${encodeURIComponent(nextCursor)}&limit=10` : "?limit=10";
      const response = await fetchCloudShieldClient(
        `/api/v1/risk/findings/${encodeURIComponent(findingId)}/evidence-snapshots${query}`,
        { schema: FrontendEvidenceSnapshotListSchema }
      );
      setItems((current) => nextCursor
        ? [...current, ...response.items.filter((item) => !current.some((existing) => existing.id === item.id))]
        : response.items);
      setCursor(response.nextCursor);
      setHasMore(response.hasMore);
    } catch (loadError) {
      setError(toApiError(loadError));
    } finally {
      setLoading(false);
      setLoadingMore(false);
    }
  }, [findingId]);

  useEffect(() => {
    void load();
  }, [load]);

  if (loading) {
    return <Section title="Evidence history"><LoadingState message="Loading immutable evidence history..." /></Section>;
  }

  if (error) {
    return (
      <Section title="Evidence history">
        <ErrorState
          title="Evidence history unavailable"
          message={error.safeMessage}
          correlationId={error.correlationId}
          onRetry={error.retryableRead ? () => void load() : undefined}
        />
      </Section>
    );
  }

  return (
    <Section
      title="Evidence history"
      description="Immutable snapshots captured when stored-inventory rules create or update this finding."
    >
      {items.length === 0 ? (
        <p className="text-sm text-slate-600">No evaluation snapshots have been captured for this finding.</p>
      ) : (
        <div className="space-y-4">
          {items.map((item) => (
            <article className="space-y-4 rounded-xl border border-slate-200 bg-slate-50 p-4" key={item.id}>
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <p className="font-semibold text-slate-900">{item.title}</p>
                  <p className="mt-1 text-sm text-slate-600">{item.summary}</p>
                </div>
                <time className="text-xs font-medium text-slate-500">{formatTimestamp(item.capturedAt)}</time>
              </div>
              <div className="flex flex-wrap items-center gap-2 text-xs text-slate-600">
                <span className="rounded-full bg-slate-200 px-2.5 py-1">{item.ruleId} v{item.ruleVersion}</span>
                <span className="rounded-full bg-slate-200 px-2.5 py-1">{item.evaluationMode}</span>
                <SourceBadge source={item.findingSource} />
                <SourceBadge source={item.resourceSource} />
                <span>Generated by rule engine</span>
                {item.sampleData ? <span className="font-semibold text-amber-700">Sample/demo data</span> : null}
              </div>
              <div className="grid gap-4 xl:grid-cols-2">
                <div>
                  <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Resource snapshot</p>
                  <pre className="max-h-80 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-100">{JSON.stringify(item.resourceSnapshot, null, 2)}</pre>
                </div>
                <div>
                  <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Evaluation context</p>
                  <pre className="max-h-80 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-100">{JSON.stringify(item.evaluationContext, null, 2)}</pre>
                </div>
              </div>
            </article>
          ))}
          {hasMore && cursor ? (
            <button
              className="cs-button-secondary"
              disabled={loadingMore}
              onClick={() => void load(cursor)}
              type="button"
            >
              {loadingMore ? "Loading..." : "Load more evidence"}
            </button>
          ) : null}
        </div>
      )}
    </Section>
  );
}
